/* Recherche : métiers rattachés à un secteur existant (sans carte d’exemple propre).
   Tapé dans la barre de recherche, un métier affiche son secteur ; un clic ouvre ce secteur. */
window.NFC = window.NFC || {};
NFC.JOBS = {
  sante: 'Acupuncteur|Agent de service hospitalier|Agent de service médico-social (ASMS)|Aide auxiliaire de puériculture|Aide médico-psychologique|Aide-soignante|Aide à domicile|Ambulancier|Aromathérapeute|Art-thérapeute|Assistant de régulation médicale|Assistant de soins en gérontologie|Assistante dentaire|Assistante médico-administrative|Assistante médicale|Audioprothésiste|Auxiliaire de puériculture|Auxiliaire de vie sociale|Accompagnant éducatif et social|Accompagnateur de personnes à mobilité réduite|Accueillant familial|Brancardier|Chiropracteur|Conseiller en phytothérapie|Diététicien|Délégué pharmaceutique|Visiteur médical|Ergothérapeute|Ergonome|Étiopathe|Hydrothérapeute|Hypnothérapeute|Infirmier|Infirmière|Infirmier anesthésiste|Infirmier de bloc opératoire|Infirmier de recherche clinique|Kinésithérapeute|Physiothérapeute|Manipulateur radio|Naturopathe|Nutritionniste|Oculariste|Opticien-lunetier|Optométriste|Orthophoniste|Orthoptiste|Orthopédiste|Ostéopathe|Pharmacien|Phytothérapeute|Podo-orthésiste|Préparateur en pharmacie|Prothésiste dentaire|Prothésiste-orthésiste|Psychologue|Psychologue pour enfants|Psychomotricien|Psychopraticien|Puéricultrice|Pédicure-podologue|Relaxologue|Réflexologue|Sage-femme|Secrétaire dentaire|Secrétaire médicale|Secrétaire pharmaceutique|Télésecrétaire médicale|Sophrologue|Technicien de laboratoire|Assistante sociale|Conseiller conjugal et familial|Médiateur familial|Technicien de l’intervention sociale et familiale|Conseiller en économie sociale et familiale|Responsable-coordonnateur services au domicile',
  conseil: 'Actuaire|Agent de gestion comptable|Analyste financier|Assistant comptable|Assistant de justice|Assistante juridique|Auditeur|Avocat|Chargé d’accueil en agence bancaire|Chargé de clientèle particulier|Chargé de clientèle professionnel|Chargé de recouvrement|Chef comptable|Commissaire aux comptes|Comptable|Conseiller en assurance|Contrôleur de gestion|Courtier d’assurances|Courtier en prêts immobiliers|Directeur d’agence bancaire|Directeur financier (DAF)|Expert d’assurance|Expert-comptable|Fiscaliste|Gestionnaire de patrimoine|Gestionnaire de portefeuille|Gestionnaire de paie|Assistante paie|Responsable paie|Greffier|Juriste|Juriste en droit immobilier|Notaire|Trader|Trésorier|Secrétaire comptable|Détective privé|Écrivain public|Agent de recouvrement du trésor|Agent des finances publiques|Contrôleur des finances publiques|Consultant RH|Directeur des ressources humaines|Responsable des ressources humaines|Responsable rémunération|Chasseur de têtes|Chargé de recrutement|Assistant recrutement|Talent acquisition manager|Assistante RH|Chief happiness officer|Responsable QVCT',
  pro: 'Account manager|Acheteur|Acheteur industriel|Adjoint administratif|Agent commercial|Agent de constatation des douanes|Agent de production agroalimentaire|Agent de prévention et de médiation|Agent de sécurité|Agent d’escale aéroportuaire|Animateur QSE|Assistant import-export|Assistant à maîtrise d’ouvrage|Assistante commerciale|Assistante de direction|Assistante de gestion PME|Attaché commercial|Attaché de presse|Brand manager|Business analyst|Business developer|Cadet de la République|Caissier|Cariste|Chargé de production|Chef de produit|Chef de projet RSE|Chef de projet MOA|Chef de rayon|Chef de secteur|Chef des ventes|Chief transformation officer|Commercial|Commissaire de police|Concierge d’entreprise|Conducteur de ligne de production|Conducteur de trains|Conducteur de métro|Conseiller pénitentiaire d’insertion et de probation|Contrôleur aérien|Contrôleur des douanes|Contrôleur du travail|Convoyeur de fonds|Croupier|Directeur commercial|Directeur de communication|Directeur des services pénitentiaires|Directeur marketing|Déclarant en douane|Éboueur|Ethical sourcing officer|Facility manager|Facteur|Garde du corps|Gardien de la paix|Policier|Gendarme|Gestionnaire de carrière|Gouvernante de maison|Majordome|Hôtesse d’accueil|Hôtesse de l’air|Steward|Pilote de ligne|Inspecteur des douanes|Lieutenant de police|Logisticien|Magasinier|Manutentionnaire|Météorologue|Métrologue|Océanologue|Hydrobiologiste|Entomologiste|Cartographe|Géomaticien|Office manager|Officier d’état civil|Opérateur de production|Pompier|Policier adjoint|Préparateur de commandes|Project manager|Chef de projet|Responsable d’ordonnancement|Responsable des ventes (sales manager)|Responsable d’exploitation|Responsable QHSE|Responsable qualité|Réceptionniste|Rédacteur territorial|Rudologue|Sales development representative|Secrétaire administratif|Secrétaire|Secrétaire de mairie|Social seller|Surveillant pénitentiaire|Technico-commercial|Technicien qualité|Technicien d’exploitation de l’eau|Technicien de l’environnement|Technicien de mesure de la pollution|Conseiller en environnement|VRP|Yield manager',
  education: 'Accompagnant d’élève en situation de handicap (AESH)|Adjoint d’animation|Agent de crèche|Auxiliaire de crèche|Aide-éducateur|Animateur petite enfance|Animateur pédagogique|Animateur de vacances|Animateur socioculturel|Assistant d’éducation|Assistant familial|Assistante maternelle|ATSEM|Auxiliaire de vie scolaire|Auxiliaire parentale|Assistante de formation|Bibliothécaire|Coach scolaire|Conseiller d’orientation-psychologue|Conseiller principal d’éducation (CPE)|Conseiller en insertion professionnelle|Conseiller en évolution professionnelle|Consultant en bilan de compétences|Directeur d’école|Directeur de crèche|Directeur de centre de vacances|Documentaliste|Éducateur de jeunes enfants|Éducateur de la protection judiciaire de la jeunesse|Éducateur spécialisé|Encadrant technique d’insertion|Formateur pour adultes|Médiateur culturel|Moniteur-éducateur|Professeur d’enseignement général au lycée|Professeur d’enseignement technologique|Professeur en lycée agricole|Professeur en lycée professionnel|Professeur d’anglais|Professeur d’éducation physique (EPS)|Professeur d’espagnol|Professeur de collège ou lycée|Professeur des écoles|Enseignant|Proviseur|Principal de collège|Psychologue scolaire|Responsable formation',
  freelance: 'Administrateur cybersécurité|Administrateur de base de données (DBA)|Administrateur réseau|Analyste SOC|Architecte réseaux|Assistant marketing|Bug bounty hunter|Chargé de communication digitale|Chargé de veille|Chef de projet en intelligence artificielle|Chef de projet marketing digital|Chef de projet web|Conseiller numérique|Consultant data|Consultant en cybersécurité|Consultant marketing|Consultant SEO|Content manager|Créateur d’environnements virtuels|Cryptologue|Data analyst|Data architect|Data engineer|Data product manager|Data scientist|DevOps|Développeur|Développeur full stack|Développeur mobile|Développeur multimédia|Évaluateur de la sécurité informatique|Expert en cybersécurité|Fabmanager|Game designer|Hacker éthique|Imprimeur 3D|Intégrateur web|Développeur front-end|Journaliste|Journaliste sportif|Machine learning engineer|Pentester|Product builder no code|Responsable de la sécurité des systèmes d’information (RSSI)|Responsable marketing digital|Roboticien|Rédacteur web|Social media manager|Technicien assistant informatique|Technicien systèmes et réseaux|Testeur de jeux vidéo|Traducteur-interprète|Traffic manager|UI designer|UX designer|Web analyste|Webmarketer|Webmaster',
  immobilier: 'Administrateur de biens|Agent immobilier|Assistant immobilier|Chasseur de biens immobiliers|Consultant en immobilier d’entreprise|Diagnostiqueur immobilier|Expert immobilier|Gardien d’immeuble|Concierge d’immeuble|Gestionnaire de copropriété|Gestionnaire immobilier|Gestionnaire locatif|Mandataire immobilier|Marchand de biens|Négociateur immobilier|Promoteur immobilier|Responsable de projets immobiliers',
  archi: 'Architecte|Architecte d’intérieur|BIM coordinateur|BIM manager|BIM modeleur|Coach déco|Concepteur vendeur de cuisine|Décorateur d’intérieur|Décoratrice d’intérieur|Designer d’espace|Dessinateur projeteur|Économiste de la construction|Home stager|Paysagiste|Urbaniste|Géomètre topographe|Géotechnicien|Maquettiste',
  artisans: 'Acousticien|Agent de maintenance des bâtiments|Agent d’entretien|Ajusteur-monteur|Ascensoriste|Auditeur énergétique|Automaticien|Bétonneur|Bûcheron|Carreleur|Chapiste|Charpentier|Charpentier métallique|Chaudronnier|Chauffagiste|Installateur thermique|Chef d’équipe BTP|Chef de chantier|Chef de projet en rénovation énergétique|Coffreur-bancheur|Conducteur de travaux|Conducteur d’engins de chantier|Conseiller en rénovation énergétique|Cordiste|Courtier en travaux|Couvreur-zingueur|Dépanneur électroménager|Dératiseur|Domoticien|Échafaudeur|Élagueur-grimpeur|Électricien|Électromécanicien|Enduiseur-façadier|Étancheur|Ébéniste|Forgeron|Frigoriste|Grutier|Hydraulicien|Immoticien|Installateur de panneaux solaires|Installateur de pompe à chaleur|Jardinier|Maçon|Marbrier|Mécatronicien|Menuisier|Monteur-câbleur|Monteur raccordeur de fibre optique|Mouleur-noyauteur|Peintre en bâtiment|Peintre en décor|Pisciniste|Plombier-chauffagiste|Plâtrier|Pontier|Projeteur de polyuréthane|Ramoneur|Serrurier|Soudeur|Staffeur-ornemaniste|Tableautier|Tailleur de pierre|Tapissier|Technicien de maintenance CVC|Technicien de maintenance industrielle|Terrassier|Tourneur-fraiseur|Vitrailliste',
  beaute: 'Agent thermal|Barbier|Coach beauté|Coach bien-être|Coiffeur|Coiffeuse|Coiffeur coloriste|Conseiller en image|Conseillère de vente beauté|Dermographe|Esthéticienne|Facialiste|Manucure|Maquilleur professionnel|Perruquier-posticheur|Praticien massage|Massothérapeute|Prothésiste ongulaire|Responsable de salon de coiffure|Socio-esthéticienne|Spa manager|Spa praticien|Visagiste',
  coaching: 'Agent de joueur|Arbitre|Coach couple|Coach de vie|Coach en entreprise|Coach nutrition|Coach parental|Coach professionnel|Coach sportif|Entraîneur de football|Entraîneur de rugby|Love coach|Maître-nageur|Moniteur de tennis|Préparateur mental|Psychologue du sport|Préparateur physique|Professeur de sport|Professeur de yoga',
  restaurant: 'Barista|Barman|Barmaid|Chef cuisinier|Chef de partie|Chef de rang|Commis de cuisine|Crêpier|Cuisinier|Cuisinier de collectivité|Écailler|Gérant de restauration collective|Maître d’hôtel|Mixologue|Pizzaïolo|Second de cuisine|Serveur|Serveuse|Sommelier',
  producteurs: 'Agriculteur|Apiculteur|Aquaculteur|Arboriculteur|Biscuitier|Boucher-charcutier|Boulanger|Brasseur|Cake designer|Caviste|Chef de culture|Chef pâtissier|Chocolatier|Conchyliculteur|Conducteur de machines agricoles|Confiseur|Conseiller agricole|Courtier en vin et spiritueux|Distillateur|Fromager-crémier|Garde-chasse|Garde forestier|Garde-pêche|Glacier|Horticulteur|Maraîcher|Mareyeur|Marin pêcheur|Maître de chai|Meunier|Mytiliculteur|Négociant en vin|Œnologue|Ouvrier agricole|Pisciculteur|Poissonnier|Pâtissier|Pépiniériste|Saunier|Sylviculteur|Tonnelier|Torréfacteur|Tourier|Vendeur en alimentation|Vigneron|Viticulteur|Zythologue',
  evenementiel: 'Chef de projet événementiel|Conseiller funéraire|Designer floral|Décorateur floral|Maître de cérémonie funéraire|Porteur funéraire|Scénographe|Thanatopracteur|Traiteur|Wedding planner',
  portfolio: 'Cadreur|Céramiste|Designer textile|Directeur artistique|Illustrateur|Infographiste|Modéliste|Monteur vidéo|Motion designer|Photographe|Photographe animalier|Pilote de drone|Plasticien|Restaurateur d’œuvres d’art|Sérigraphe|Styliste de mode|Tatoueur|Vidéaste|Webdesigner',
  musique: 'Agent artistique|Cascadeur|Costumier|Ingénieur du son|Luthier|Magicien',
  influence: 'Community manager|Créateur de contenu UGC|Influenceur',
  hebergement: 'Concierge d’hôtel|Directeur d’hôtel|Gouvernante d’étage|Gérant de camping|Voiturier',
  tourisme: 'Agent de réservation|Agent de voyages|Animateur de tourisme local|Chargé de mission tourisme|Chef de produit touristique|Chef de projet touristique|Chef de projet en tourisme d’affaires|Conseiller de voyages|Directeur d’office de tourisme|Forfaitiste|Guide touristique',
  animaux: 'Aquariologiste|Auxiliaire de santé animale|Auxiliaire vétérinaire|Cavalier soigneur|Chef animalier|Comportementaliste animalier|Comportementaliste félin|Éducateur canin|Éducateur de chiens guides|Éleveur de chiens et chats|Éleveur de chevaux|Éleveur de NAC|Fauconnier|Hydrothérapeute canin|Jockey|Maréchal-ferrant|Masseur pour chien|Maître-chien|Ostéopathe animalier|Palefrenier|Pet sitter|Physiothérapeute animalier|Secrétaire vétérinaire|Sellier-harnacheur|Soigneur animalier|Taxidermiste|Toiletteur canin|Vendeur en animalerie|Zoologiste|Zoothérapeute',
  boutiques: 'Armurier|Bijoutier-joaillier|Bottier|Chapelier|Cordonnier|Couturière|Coutelier|Créateur d’abat-jour|Faïencier|Fleuriste|Gantier|Gemmologue|Horloger|Libraire|Maroquinier|Modiste|Nez créateur de parfum|Orfèvre|Parfumeur|Responsable de magasin|Sellier|Shaper|Souffleur de verre|Vendeur|Vendeuse|Visual merchandiser',
  auto: 'Carrossier|Chauffeur de bus|Chauffeur de taxi|Chauffeur livreur|Chauffeur personnel|Chauffeur routier|Contrôleur technique automobile|Électronicien automobile|Mécanicien automobile|Mécanicien de maintenance aéronautique|Mécanicien moto|Mécanicien poids lourd|Mécanicien vélo|Moniteur d’auto-école',
};
