/* Secteur « Éducation » : 10 métiers (étudiant, professeur, stagiaire, éducateur, tuteur, chargé de cours, conseiller d’orientation, orthopédagogue, directeur d’école, formateur) (FR = Québec, EN = États-Unis).
   Chaque métier a son exemple complet ; les sections du secteur sont communes et s’affichent selon le métier.
   Photos : Unsplash (licence gratuite), affichées depuis images.unsplash.com. */
(function () {
  'use strict';

  const hx = (h) => [0, 2, 4].map((i) => parseInt(h.slice(1).substr(i, 2), 16));
  const mix = (a, b, t) => '#' + hx(a).map((v, i) => Math.round(v + (hx(b)[i] - v) * t).toString(16).padStart(2, '0')).join('');
  const pal = (name, p, a) => ({ name, p, a, bg: mix(p, '#ffffff', 0.955), sf: '#ffffff', tx: mix(p, '#0b0b0f', 0.86), mu: mix(p, '#6b6b72', 0.8), ln: mix(p, '#ffffff', 0.87) });
  const U = (id, w = 640) => `https://images.unsplash.com/photo-${id}?w=${w}&q=70&auto=format&fit=crop`;
  const B = (key, type, title, extra) => Object.assign({ key, type, title }, extra || {});

  /* Sections du secteur (chaque métier choisit celles qu’il affiche et peut renommer leur titre) */
  const BLOCKS = [
    B('about', 'text', 'Présentation', { help: '80 à 150 mots conseillés' }),
    B('services', 'list', 'Services', { price: true, help: 'Cours, ateliers, accompagnement… avec vos tarifs si vous le souhaitez' }),
    B('parcours', 'list', 'Parcours', { help: 'Formation, diplômes, expériences' }),
    B('skills', 'tags', 'Compétences', { icon: 'check' }),
    B('projects', 'cards', 'Projets', { help: 'Travaux, réalisations, projets d’équipe' }),
    B('gallery', 'gallery', 'En images'),
    B('booking', 'action', 'Rendez-vous', { cta: 'Prendre rendez-vous', icon: 'cal', help: 'Lien Calendly ou équivalent' }),
    B('docs', 'links', 'CV et documents', { help: 'CV, portfolio, lettre de recommandation…' }),
    B('langs', 'tags', 'Langues', { icon: 'globe' }),
    B('hours', 'hours', 'Disponibilités'),
    B('location', 'location', 'Où me trouver'),
    B('reviews', 'reviews', 'Recommandations'),
    B('form', 'form', 'Me contacter', { cta: 'Me contacter', help: 'Formulaire envoyé à votre adresse courriel' }),
  ];

  /* Exemple complet d’un métier dans une langue. x : textes ; M : photos. Une section absente de x reste masquée. */
  function demo(x, M) {
    const on = (k) => !!x[k];
    const t = (k) => (x[k] && x[k].title) || '';
    return {
      primary: x.primary || 'save',
      identity: { name: x.id[0], role: x.id[1], specialty: x.id[2], company: x.id[3] || '', photo: U(M.portrait, 400), logo: '', cover: U(M.cover, 1200) },
      contact: { phone: x.ct[0], whatsapp: '', email: x.ct[1], website: x.ct[2] || '' },
      socials: Object.assign({ linkedin: '', instagram: '', facebook: '', tiktok: '', youtube: '' }, x.so || { linkedin: 'https://linkedin.com/' }),
      blocks: {
        about: { on: true, title: x.about[0], text: x.about[1] },
        services: { on: on('services'), title: t('services'), items: ((x.services || {}).items || []).map(([a, b, p]) => ({ t: a, d: b, p: p || '' })) },
        parcours: { on: on('parcours'), title: t('parcours'), items: ((x.parcours || {}).items || []).map(([a, b]) => ({ t: a, d: b, p: '' })) },
        skills: { on: on('skills'), title: t('skills'), tags: (x.skills || {}).tags || '', text: '' },
        projects: { on: on('projects'), title: t('projects'), items: ((x.projects || {}).items || []).map(([a, b], i) => ({ t: a, d: b, p: '', img: U(M.cards[i]), url: '' })) },
        gallery: { on: on('gallery'), title: t('gallery'), images: M.gal.map((id, i) => ({ src: U(id), cap: ((x.gallery || {}).caps || [])[i] || '' })) },
        booking: { on: on('booking'), title: t('booking'), label: (x.booking || {}).label || '', url: (x.booking || {}).url || '', text: (x.booking || {}).text || '' },
        docs: { on: on('docs'), title: t('docs'), items: ((x.docs || {}).items || []).map(([label, url]) => ({ label, url })) },
        langs: { on: on('langs'), title: t('langs'), tags: (x.langs || {}).tags || '', text: '' },
        hours: { on: on('hours'), title: t('hours'), rows: ((x.hours || {}).rows || []).map(([d, h]) => ({ d, h })), note: (x.hours || {}).note || '' },
        location: { on: on('location'), title: t('location'), map: true, address: (x.location || {}).address || '', access: (x.location || {}).access || '' },
        reviews: { on: on('reviews'), title: t('reviews'), items: ((x.reviews || {}).items || []).map(([n, r, tt]) => ({ n, r, t: tt, s: 5 })) },
        form: { on: on('form'), title: t('form'), email: x.ct[1], text: (x.form || {}).text || '', files: true },
      },
    };
  }
  const media = (M, x) => ({ portrait: U(M.portrait, 400), cover: U(M.cover, 1200), gallery: M.gal.map((id, i) => ({ src: U(id), cap: ((x.gallery || {}).caps || [])[i] || '' })), cards: M.cards.map((id) => U(id)) });
  const P = (o) => ({ id: o.id, icon: o.icon, n: o.n, ex: o.ex, rec: o.rec, palettes: o.pal, demo: demo(o.fr, o.M), demoEn: demo(o.en, o.M), media: media(o.M, o.fr) });

  const PROFILES = [
    /* ---------- Étudiant ---------- */
    P({ id: 'etudiant', icon: 'graduation-cap', rec: 'd4', n: ['Étudiant', 'Student'], ex: ['Cégep, université, recherche de stage', 'College, university, internship search'],
      pal: [pal('Bleu campus', '#1d4ed8', '#fbbf24'), pal('Vert', '#166534', '#a3e635'), pal('Bordeaux', '#7f1d1d', '#fca5a5'), pal('Encre', '#111827', '#60a5fa'), pal('Violet', '#5b21b6', '#f0abfc'), pal('Sarcelle', '#115e59', '#fcd34d')],
      M: { portrait: '1573496359142-b8d87734a5a2', cover: '1606761568499-6d2451b23c66', gal: ['1741699428220-65f37f3fbbcb', '1515378960530-7c0da6231fb1', '1623461487986-9400110de28e', '1562774053-701939374585'], cards: ['1531297484001-80022131f5a1', '1518314916381-77a37c2a49ae', '1614741118887-7a4ee193a5fa'] },
      fr: { id: ['Emma Collins', 'Étudiante en génie logiciel', 'Baccalauréat, 3e année · À la recherche d’un stage d’été 2027', 'Université de Sherbrooke'], ct: ['+1 819 555-0114', 'emma.collins@courriel.ca', 'emmacollins.dev'], so: { linkedin: 'https://linkedin.com/in/', instagram: '', youtube: '' },
        primary: 'form',
        about: ['Qui suis-je', 'Étudiante en 3e année de génie logiciel, je me passionne pour le développement d’applications web et l’intelligence artificielle.\nJe cherche un stage d’été de 12 à 16 semaines dans une équipe où je pourrai apprendre et contribuer dès le premier jour.'],
        parcours: { title: 'Formation et expériences', items: [['Baccalauréat en génie logiciel · 2024 – 2028', 'Moyenne cumulative 3,8 / 4,3 · Liste du doyen'], ['Stage en développement web · été 2026', 'Agence numérique · application de réservation en React'], ['Tutrice en programmation · depuis 2025', 'Aide aux étudiants de 1re année, 6 h par semaine']] },
        skills: { title: 'Compétences', tags: 'JavaScript, React, Python, SQL, Git, Travail d’équipe, Gestion de projet Agile' },
        projects: { title: 'Projets', items: [['Application de covoiturage étudiant', 'Projet de session · React et Node.js · 400 utilisateurs'], ['Robot suiveur de ligne', 'Compétition de robotique · 2e place'], ['Tableau de bord météo', 'Projet personnel · API publique et graphiques']] },
        docs: { title: 'CV et portfolio', items: [['Mon CV (PDF)', 'https://example.com/cv.pdf'], ['Portfolio GitHub', 'https://github.com/'], ['Relevé de notes', 'https://example.com/releve.pdf']] },
        langs: { title: 'Langues', tags: 'Français (langue maternelle), Anglais (courant), Espagnol (intermédiaire)' },
        gallery: { title: 'Vie étudiante', caps: ['À la bibliothèque', 'Projet d’équipe', 'Remise des diplômes du cégep', 'Le campus'] },
        reviews: { title: 'Recommandations', items: [['Pr. Michael Grant', 'Professeur, génie logiciel', 'Emma est rigoureuse, curieuse et très appréciée de son équipe. Je la recommande sans hésiter.'], ['Jennifer Lee', 'Superviseure de stage', 'Autonome dès la deuxième semaine, Emma a livré une fonctionnalité utilisée par tous nos clients.']] },
        form: { title: 'Me proposer un stage', text: 'Vous avez un stage ou un projet à me proposer ? Écrivez-moi, je vous réponds sous 48 h.' } },
      en: { id: ['Emma Collins', 'Software engineering student', 'Junior year · Looking for a summer 2027 internship', 'University of Michigan'], ct: ['+1 734 555-0114', 'emma.collins@email.com', 'emmacollins.dev'], so: { linkedin: 'https://linkedin.com/in/' },
        primary: 'form',
        about: ['About me', 'Junior in software engineering, passionate about web development and artificial intelligence.\nI’m looking for a 12 to 16-week summer internship on a team where I can learn and contribute from day one.'],
        parcours: { title: 'Education & experience', items: [['B.S. in Software Engineering · 2024 – 2028', 'GPA 3.8 / 4.0 · Dean’s List'], ['Web development intern · summer 2026', 'Digital agency · booking app built with React'], ['Programming tutor · since 2025', 'Helping first-year students, 6 hours a week']] },
        skills: { title: 'Skills', tags: 'JavaScript, React, Python, SQL, Git, Teamwork, Agile project management' },
        projects: { title: 'Projects', items: [['Student carpool app', 'Course project · React and Node.js · 400 users'], ['Line-following robot', 'Robotics competition · 2nd place'], ['Weather dashboard', 'Side project · public API and charts']] },
        docs: { title: 'Resume & portfolio', items: [['My resume (PDF)', 'https://example.com/resume.pdf'], ['GitHub portfolio', 'https://github.com/'], ['Transcript', 'https://example.com/transcript.pdf']] },
        langs: { title: 'Languages', tags: 'English (native), French (fluent), Spanish (intermediate)' },
        gallery: { title: 'Campus life', caps: ['At the library', 'Team project', 'High school graduation', 'The campus'] },
        reviews: { title: 'References', items: [['Prof. Michael Grant', 'Professor, software engineering', 'Emma is rigorous, curious and well liked by her team. I recommend her without hesitation.'], ['Jennifer Lee', 'Internship supervisor', 'Independent by week two, Emma shipped a feature all our clients use.']] },
        form: { title: 'Offer me an internship', text: 'Have an internship or a project for me? Write to me, I’ll reply within 48 hours.' } } }),

    /* ---------- Professeur ---------- */
    P({ id: 'professeur', icon: 'presentation', rec: 'd2', n: ['Professeur', 'Teacher'], ex: ['Enseignant, cours privés, tutorat', 'Teacher, private lessons, tutoring'],
      pal: [pal('Tableau vert', '#1f4d3a', '#f2d16b'), pal('Bleu marine', '#1e3a5f', '#f4a261'), pal('Brique', '#8c3b2a', '#f6d186'), pal('Ardoise', '#2f3a45', '#9ad1d4'), pal('Prune', '#4a2545', '#f2c57c'), pal('Crayon', '#7a5a1e', '#ffd166')],
      M: { portrait: '1574281570877-bd815ebb50a4', cover: '1509062522246-3755977927d7', gal: ['1580582932707-520aed937b7b', '1596495577886-d920f1fb7238', '1503676260728-1c00da094a0b', '1565598621680-94ac0c22b148'], cards: ['1596495577886-d920f1fb7238', '1565598621680-94ac0c22b148', '1503676260728-1c00da094a0b'] },
      fr: { id: ['Daniel Harper', 'Professeur de mathématiques', 'Secondaire et cégep · Cours privés et préparation aux examens', 'École secondaire du Plateau'], ct: ['+1 514 555-0128', 'daniel.harper@courriel.ca', 'profharper.ca'], so: { linkedin: 'https://linkedin.com/in/', youtube: 'https://youtube.com/' },
        primary: 'booking',
        about: ['Ma façon d’enseigner', 'Professeur de mathématiques depuis 14 ans, j’aide les élèves à reprendre confiance et à comprendre plutôt qu’à apprendre par cœur.\nEn plus de ma classe, j’offre des cours privés en ligne ou à domicile, du secondaire 1 au cégep.'],
        services: { title: 'Cours et tutorat', items: [['Cours privé · secondaire', 'En ligne ou à domicile, 60 minutes', '55 $'], ['Cours privé · cégep', 'Calcul, algèbre linéaire, statistiques', '65 $'], ['Préparation aux examens', 'Forfait 5 séances avant l’examen du ministère', '250 $'], ['Petit groupe (3 à 5 élèves)', '90 minutes, par élève', '30 $']] },
        parcours: { title: 'Parcours', items: [['Enseignant au secondaire · depuis 2012', 'Mathématiques, secondaire 4 et 5'], ['Baccalauréat en enseignement des mathématiques', 'Université du Québec à Montréal'], ['Correcteur aux examens du ministère', 'Depuis 2018']] },
        booking: { title: 'Rencontres et cours', label: 'Réserver une séance', url: 'https://calendly.com/', text: 'Parents et élèves : réservez un cours privé ou une rencontre de suivi.' },
        docs: { title: 'Ressources', items: [['Plan de cours · Secondaire 4 (PDF)', 'https://example.com/plan.pdf'], ['Exercices de révision', 'https://example.com/exercices'], ['Ma chaîne YouTube de capsules', 'https://youtube.com/']] },
        hours: { title: 'Disponibilités', rows: [['Lundi – Jeudi', '16 h – 20 h'], ['Samedi', '9 h – 13 h']], note: 'Cours en ligne ou à domicile (Plateau, Rosemont, Outremont)' },
        reviews: { title: 'Ce qu’en disent les familles', items: [['Nathalie B.', 'Mère d’un élève de secondaire 5', 'Mon fils est passé de 58 % à 81 % en un trimestre. Merci pour votre patience !'], ['Alex T.', 'Étudiant au cégep', 'Il explique le calcul différentiel mieux que n’importe quel manuel.']] },
        form: { title: 'Me poser une question', text: 'Une question sur un cours, un niveau ou une matière ? Écrivez-moi.' } },
      en: { id: ['Daniel Harper', 'Math teacher', 'High school & college · Private lessons and test prep', 'Lincoln High School'], ct: ['+1 312 555-0128', 'daniel.harper@email.com', 'mrharpermath.com'], so: { linkedin: 'https://linkedin.com/in/', youtube: 'https://youtube.com/' },
        primary: 'booking',
        about: ['How I teach', 'A math teacher for 14 years, I help students regain confidence and truly understand instead of memorizing.\nBesides my classroom, I offer private lessons online or at home, from middle school to college.'],
        services: { title: 'Lessons & tutoring', items: [['Private lesson · high school', 'Online or at home, 60 minutes', '$60'], ['Private lesson · college', 'Calculus, linear algebra, statistics', '$70'], ['SAT / ACT math prep', '5-session package', '$275'], ['Small group (3 to 5 students)', '90 minutes, per student', '$35']] },
        parcours: { title: 'Background', items: [['High school math teacher · since 2012', 'Algebra II, Pre-calculus'], ['B.A. in Mathematics Education', 'University of Illinois'], ['AP Calculus exam reader', 'Since 2018']] },
        booking: { title: 'Meetings & lessons', label: 'Book a session', url: 'https://calendly.com/', text: 'Parents and students: book a private lesson or a progress meeting.' },
        docs: { title: 'Resources', items: [['Algebra II syllabus (PDF)', 'https://example.com/syllabus.pdf'], ['Practice problems', 'https://example.com/practice'], ['My YouTube lessons', 'https://youtube.com/']] },
        hours: { title: 'Availability', rows: [['Monday – Thursday', '4 pm – 8 pm'], ['Saturday', '9 am – 1 pm']], note: 'Online or at home (Lincoln Park, Lakeview)' },
        reviews: { title: 'What families say', items: [['Nancy B.', 'Parent of a senior', 'My son went from a D to a B+ in one semester. Thank you for your patience!'], ['Alex T.', 'College student', 'He explains calculus better than any textbook.']] },
        form: { title: 'Ask me a question', text: 'A question about a lesson, a level or a subject? Write to me.' } } }),

    /* ---------- Stagiaire ---------- */
    P({ id: 'stagiaire', icon: 'briefcase', rec: 'd1', n: ['Stagiaire', 'Intern'], ex: ['Stage en entreprise, premier emploi', 'Internship, first job'],
      pal: [pal('Bleu pro', '#1e40af', '#93c5fd'), pal('Graphite', '#27272a', '#a3e635'), pal('Émeraude', '#065f46', '#6ee7b7'), pal('Corail', '#9a3412', '#fdba74'), pal('Indigo', '#3730a3', '#c4b5fd'), pal('Pétrole', '#134e4a', '#fcd34d')],
      M: { portrait: '1624797432677-6f803a98acb3', cover: '1517048676732-d65bc937f952', gal: ['1758691736545-5c33b6255dca', '1542744173-8e7e53415bb0', '1563986768494-4dee2763ff3f', '1517245386807-bb43f82c33c4'], cards: ['1683721003111-070bcc053d8b', '1563986768494-4dee2763ff3f', '1758691736545-5c33b6255dca'] },
      fr: { id: ['Lucas Bennett', 'Stagiaire en marketing numérique', 'Fin de stage en décembre · Disponible pour un premier emploi en janvier 2027', 'Agence Lumino'], ct: ['+1 418 555-0147', 'lucas.bennett@courriel.ca', ''], so: { linkedin: 'https://linkedin.com/in/', instagram: 'https://instagram.com/' },
        primary: 'save',
        about: ['Présentation', 'Diplômé en marketing, je termine un stage de 6 mois en marketing numérique où je gère des campagnes publicitaires et les réseaux sociaux de cinq clients.\nJe cherche un premier poste de coordonnateur marketing dans la région de Québec.'],
        parcours: { title: 'Parcours', items: [['Stagiaire en marketing numérique · 2026', 'Agence Lumino · campagnes Meta et Google, rapports mensuels'], ['Baccalauréat en marketing · 2023 – 2026', 'Université Laval · concentration marketing numérique'], ['Commis aux ventes · 2021 – 2023', 'Boutique de sport · service à la clientèle']] },
        skills: { title: 'Compétences', tags: 'Meta Ads, Google Ads, Google Analytics, Canva, Rédaction, Réseaux sociaux, Excel' },
        projects: { title: 'Réalisations de stage', items: [['Campagne de lancement', '+42 % d’abonnés Instagram en 3 mois pour un café local'], ['Publicité ciblée', 'Coût par contact réduit de 35 % pour une clinique'], ['Rapport de performance', 'Tableau de bord mensuel pour 5 clients']] },
        docs: { title: 'CV et recommandations', items: [['Mon CV (PDF)', 'https://example.com/cv.pdf'], ['Lettre de recommandation', 'https://example.com/lettre.pdf'], ['Certification Google Ads', 'https://example.com/certif']] },
        langs: { title: 'Langues', tags: 'Français, Anglais' },
        reviews: { title: 'Recommandations', items: [['Rachel Morgan', 'Directrice, Agence Lumino', 'Lucas a pris en charge des clients réels dès le 2e mois. Fiable, créatif et à l’écoute.'], ['Kevin Shaw', 'Client, Café Le Moulin', 'Nos réseaux sociaux n’ont jamais été aussi vivants.']] },
        form: { title: 'Me proposer un poste', text: 'Vous recrutez ? Écrivez-moi : je peux vous envoyer mon portfolio complet.' } },
      en: { id: ['Lucas Bennett', 'Digital marketing intern', 'Internship ends in December · Available for a first job in January 2027', 'Lumino Agency'], ct: ['+1 512 555-0147', 'lucas.bennett@email.com', ''], so: { linkedin: 'https://linkedin.com/in/', instagram: 'https://instagram.com/' },
        primary: 'save',
        about: ['About me', 'A marketing graduate finishing a 6-month digital marketing internship, where I run ad campaigns and social media for five clients.\nI’m looking for a first marketing coordinator role in the Austin area.'],
        parcours: { title: 'Background', items: [['Digital marketing intern · 2026', 'Lumino Agency · Meta and Google campaigns, monthly reports'], ['B.B.A. in Marketing · 2023 – 2026', 'University of Texas · digital marketing concentration'], ['Sales associate · 2021 – 2023', 'Sporting goods store · customer service']] },
        skills: { title: 'Skills', tags: 'Meta Ads, Google Ads, Google Analytics, Canva, Copywriting, Social media, Excel' },
        projects: { title: 'Internship results', items: [['Launch campaign', '+42% Instagram followers in 3 months for a local café'], ['Targeted ads', '35% lower cost per lead for a clinic'], ['Performance reporting', 'Monthly dashboard for 5 clients']] },
        docs: { title: 'Resume & references', items: [['My resume (PDF)', 'https://example.com/resume.pdf'], ['Reference letter', 'https://example.com/letter.pdf'], ['Google Ads certification', 'https://example.com/cert']] },
        langs: { title: 'Languages', tags: 'English, Spanish' },
        reviews: { title: 'References', items: [['Rachel Morgan', 'Director, Lumino Agency', 'Lucas handled real clients by month two. Reliable, creative and a great listener.'], ['Kevin Shaw', 'Client, Mill Street Café', 'Our social media has never been this lively.']] },
        form: { title: 'Offer me a job', text: 'Hiring? Write to me: I can send you my full portfolio.' } } }),

    /* ---------- Éducateur ---------- */
    P({ id: 'educateur', icon: 'baby', rec: 'd9', n: ['Éducateur', 'Educator'], ex: ['Petite enfance, garderie, éducation spécialisée', 'Early childhood, daycare, special education'],
      pal: [pal('Arc-en-ciel', '#c2410c', '#fde68a'), pal('Ciel', '#0369a1', '#fcd34d'), pal('Pomme', '#3f6212', '#fca5a5'), pal('Lilas', '#6d28d9', '#fbcfe8'), pal('Corail', '#be123c', '#fed7aa'), pal('Sable', '#7c5a3a', '#bae6fd')],
      M: { portrait: '1580894732444-8ecded7900cd', cover: '1588075592446-265fd1e6e76f', gal: ['1587323655395-b1c77a12c89a', '1484820540004-14229fe36ca4', '1549737221-bef65e2604a6', '1615489548573-8165c2c35e1b'], cards: ['1587323655395-b1c77a12c89a', '1484820540004-14229fe36ca4', '1549737221-bef65e2604a6'] },
      fr: { id: ['Sarah Mitchell', 'Éducatrice à la petite enfance', 'Service de garde en milieu familial reconnu · 6 places', 'Les Petits Explorateurs'], ct: ['+1 450 555-0163', 'sarah@petitsexplorateurs.ca', 'petitsexplorateurs.ca'], so: { facebook: 'https://facebook.com/', instagram: '' },
        primary: 'form',
        about: ['Mon service de garde', 'Éducatrice diplômée depuis 10 ans, j’accueille six enfants de 18 mois à 5 ans dans un milieu chaleureux, avec une grande cour et un programme éducatif basé sur le jeu.\nRepas maison, sorties au parc chaque jour et communication quotidienne avec les parents.'],
        services: { title: 'Le service', items: [['Place à contribution réduite', 'Du lundi au vendredi, 7 h 30 à 17 h 30', '9,35 $ / jour'], ['Repas et collations maison', 'Menu affiché chaque semaine', 'Inclus'], ['Sorties et activités', 'Parc, bibliothèque, éveil musical', 'Inclus']] },
        parcours: { title: 'Formation', items: [['Technique d’éducation à l’enfance (DEC)', 'Cégep de Saint-Jérôme'], ['Premiers soins en milieu de garde', 'Certification à jour'], ['Responsable de service de garde reconnue', 'Depuis 2016']] },
        gallery: { title: 'Nos journées', caps: ['Bricolage', 'Jeux de construction', 'L’heure du conte', 'Au parc'] },
        hours: { title: 'Heures d’ouverture', rows: [['Lundi – Vendredi', '7 h 30 – 17 h 30'], ['Samedi – Dimanche', 'Fermé']], note: '1 place disponible en janvier 2027' },
        location: { title: 'Où nous trouver', address: 'Rue des Érables, Blainville (Québec)', access: 'Adresse complète communiquée aux familles inscrites' },
        reviews: { title: 'Les parents en parlent', items: [['Jessica P.', 'Maman de Léo, 3 ans', 'Léo court vers la porte chaque matin. Sarah est douce, organisée et pleine d’idées.'], ['Mark D.', 'Papa d’Alice, 2 ans', 'Les photos et le petit mot de chaque jour nous rassurent énormément.']] },
        form: { title: 'Demande de place', text: 'Âge de votre enfant, date d’entrée souhaitée, questions : écrivez-moi, je vous rappelle pour une visite.' } },
      en: { id: ['Sarah Mitchell', 'Early childhood educator', 'Licensed family child care · 6 spots', 'Little Explorers'], ct: ['+1 503 555-0163', 'sarah@littleexplorers.com', 'littleexplorers.com'], so: { facebook: 'https://facebook.com/' },
        primary: 'form',
        about: ['My child care', 'A certified educator for 10 years, I care for six children aged 18 months to 5 in a warm home setting with a big backyard and a play-based learning program.\nHomemade meals, daily park outings and daily updates for parents.'],
        services: { title: 'The program', items: [['Full-time spot', 'Monday to Friday, 7:30 am to 5:30 pm', '$1,450 / month'], ['Homemade meals & snacks', 'Weekly menu posted', 'Included'], ['Outings & activities', 'Park, library, music', 'Included']] },
        parcours: { title: 'Training', items: [['Associate degree in Early Childhood Education', 'Portland Community College'], ['Pediatric first aid & CPR', 'Current certification'], ['Licensed family child care provider', 'Since 2016']] },
        gallery: { title: 'Our days', caps: ['Arts and crafts', 'Building games', 'Story time', 'At the park'] },
        hours: { title: 'Opening hours', rows: [['Monday – Friday', '7:30 am – 5:30 pm'], ['Saturday – Sunday', 'Closed']], note: '1 spot opening in January 2027' },
        location: { title: 'Where we are', address: 'Sellwood neighborhood, Portland, OR', access: 'Full address shared with enrolled families' },
        reviews: { title: 'What parents say', items: [['Jessica P.', 'Mom of Leo, 3', 'Leo runs to the door every morning. Sarah is gentle, organized and full of ideas.'], ['Mark D.', 'Dad of Alice, 2', 'The daily photos and notes are so reassuring.']] },
        form: { title: 'Request a spot', text: 'Your child’s age, desired start date, questions: write to me and I’ll call you back to set up a visit.' } } }),
    /* ---------- Tuteur ---------- */
    P({ id: 'tuteur', icon: 'book-open-check', rec: 'd4', n: ['Tuteur', 'Tutor'], ex: ['Aide aux devoirs, rattrapage scolaire', 'Homework help, academic support'],
      pal: [pal('Bleu ciel', '#0369a1', '#fde047'), pal('Vert', '#15803d', '#fcd34d'), pal('Corail', '#c2410c', '#bae6fd'), pal('Violet', '#6d28d9', '#fde68a'), pal('Marine', '#1e3a8a', '#fda4af'), pal('Sarcelle', '#0f766e', '#fef08a')],
      M: { portrait: '1662850886700-4ec19bd30d11', cover: '1560785496-3c9d27877182', gal: ['1585432959445-662c9bbcd91d', '1612831455359-970e23a1e4e9', '1585432959449-b1c9c8cc49ac', '1758612898701-e2f2958f219d'], cards: ['1585432959445-662c9bbcd91d', '1612831455359-970e23a1e4e9', '1758612898701-e2f2958f219d'] },
      fr: { id: ['Megan Brooks', 'Tutrice scolaire', 'Primaire et secondaire · Français, mathématiques, anglais', 'Tutorat Brooks'], ct: ['+1 418 555-0171', 'megan@tutoratbrooks.ca', 'tutoratbrooks.ca'], so: { facebook: 'https://facebook.com/' },
        primary: 'booking',
        about: ['Mon approche', 'Tutrice depuis 8 ans, j’aide les élèves du primaire et du secondaire à rattraper leur retard et à reprendre confiance.\nChaque séance commence par ce qui bloque l’élève, avec des exercices adaptés et un petit compte rendu envoyé aux parents.'],
        services: { title: 'Tarifs', items: [['Séance individuelle · primaire', '60 minutes, en ligne ou à domicile', '40 $'], ['Séance individuelle · secondaire', '60 minutes, en ligne ou à domicile', '45 $'], ['Forfait 10 séances', 'Suivi régulier toute la session', '400 $'], ['Préparation aux examens de fin d’année', '4 séances intensives', '170 $']] },
        skills: { title: 'Matières', tags: 'Français, Mathématiques, Anglais, Méthodes de travail, Préparation aux examens' },
        booking: { title: 'Réserver une séance', label: 'Choisir un créneau', url: 'https://calendly.com/', text: 'Première séance d’évaluation de 30 minutes offerte.' },
        hours: { title: 'Disponibilités', rows: [['Lundi – Jeudi', '15 h 30 – 20 h'], ['Samedi', '9 h – 12 h']], note: 'En ligne partout au Québec, à domicile à Québec et Lévis' },
        gallery: { title: 'En séance', caps: ['Lecture', 'Cours en ligne', 'Exercices', 'Révision'] },
        reviews: { title: 'Les parents en parlent', items: [['Caroline M.', 'Mère d’une élève de 6e année', 'Ma fille a repris confiance en elle et ses notes ont suivi. Merci Megan !'], ['Steve R.', 'Père d’un élève de secondaire 2', 'Les comptes rendus après chaque séance sont très appréciés.']] },
        form: { title: 'Me contacter', text: 'Niveau de l’enfant, matières, disponibilités : écrivez-moi et je vous propose un horaire.' } },
      en: { id: ['Megan Brooks', 'Academic tutor', 'Elementary to high school · Reading, math, writing', 'Brooks Tutoring'], ct: ['+1 617 555-0171', 'megan@brookstutoring.com', 'brookstutoring.com'], so: { facebook: 'https://facebook.com/' },
        primary: 'booking',
        about: ['My approach', 'A tutor for 8 years, I help elementary and high school students catch up and regain confidence.\nEvery session starts with what’s blocking the student, with tailored exercises and a short report sent to parents.'],
        services: { title: 'Rates', items: [['One-on-one · elementary', '60 minutes, online or at home', '$45'], ['One-on-one · high school', '60 minutes, online or at home', '$50'], ['10-session package', 'Regular support all semester', '$450'], ['Finals prep', '4 intensive sessions', '$190']] },
        skills: { title: 'Subjects', tags: 'Reading, Math, Writing, Study skills, Test prep' },
        booking: { title: 'Book a session', label: 'Pick a time', url: 'https://calendly.com/', text: 'Free 30-minute assessment session.' },
        hours: { title: 'Availability', rows: [['Monday – Thursday', '3:30 pm – 8 pm'], ['Saturday', '9 am – 12 pm']], note: 'Online nationwide, in-home in the Boston area' },
        gallery: { title: 'In session', caps: ['Reading', 'Online lesson', 'Practice', 'Review'] },
        reviews: { title: 'What parents say', items: [['Caroline M.', 'Mom of a 6th grader', 'My daughter regained her confidence and her grades followed. Thank you Megan!'], ['Steve R.', 'Dad of an 8th grader', 'The reports after each session are much appreciated.']] },
        form: { title: 'Contact me', text: 'Grade, subjects, availability: write to me and I’ll suggest a schedule.' } } }),

    /* ---------- Chargé de cours ---------- */
    P({ id: 'charge', icon: 'library', rec: 'd10', n: ['Chargé de cours', 'College lecturer'], ex: ['Université, cégep, recherche', 'University, college, research'],
      pal: [pal('Bordeaux', '#6b1d2a', '#d4b483'), pal('Marine & or', '#1b2a4a', '#c8a24a'), pal('Vert sapin', '#1f4d3a', '#e2c78f'), pal('Ardoise', '#2f3a45', '#b9c6d2'), pal('Noir', '#1c1917', '#d6b36a'), pal('Prune', '#4a2545', '#e8c39e')],
      M: { portrait: '1758685847747-597ce085906e', cover: '1736066330610-c102cab4e942', gal: ['1641735123823-90856d1efd39', '1562774053-701939374585', '1741699428220-65f37f3fbbcb', '1606761568499-6d2451b23c66'], cards: ['1741699428220-65f37f3fbbcb', '1641735123823-90856d1efd39', '1562774053-701939374585'] },
      fr: { id: ['Dre Olivia Grant', 'Chargée de cours en histoire', 'Histoire du Québec et de l’Amérique du Nord · Conférencière', 'Université de Montréal'], ct: ['+1 514 555-0182', 'olivia.grant@courriel.ca', 'oliviagrant.ca'], so: { linkedin: 'https://linkedin.com/in/', youtube: 'https://youtube.com/' },
        primary: 'form',
        about: ['Enseignement et recherche', 'Docteure en histoire, j’enseigne l’histoire du Québec et de l’Amérique du Nord au premier cycle depuis 2015.\nJe donne aussi des conférences grand public dans les bibliothèques, les musées et les entreprises.'],
        services: { title: 'Cours et conférences', items: [['HST 1020 · Histoire du Québec', 'Premier cycle, session d’automne'], ['HST 2310 · Amérique du Nord, 1760 – 1867', 'Premier cycle, session d’hiver'], ['Conférence grand public', '60 à 90 minutes, sur demande', 'Sur demande']] },
        parcours: { title: 'Parcours', items: [['Doctorat en histoire · 2015', 'Thèse sur les réseaux commerciaux du Saint-Laurent'], ['Chargée de cours · depuis 2015', 'Département d’histoire'], ['Commissaire d’exposition · 2022', 'Musée d’histoire régionale']] },
        projects: { title: 'Publications', items: [['Les marchands du fleuve', 'Livre, 2021 · Prix de l’histoire régionale'], ['Article : Le commerce des fourrures', 'Revue d’histoire, 2023'], ['Balado : L’histoire en 20 minutes', '45 épisodes']] },
        docs: { title: 'Documents', items: [['Plan de cours HST 1020 (PDF)', 'https://example.com/plan.pdf'], ['Liste de publications', 'https://example.com/publications'], ['Balado', 'https://example.com/balado']] },
        hours: { title: 'Disponibilités pour les étudiants', rows: [['Mardi', '13 h – 15 h'], ['Jeudi', '10 h – 12 h']], note: 'Bureau C-3120 ou en visioconférence, sur rendez-vous' },
        reviews: { title: 'Ce qu’en disent les étudiants', items: [['Antoine L.', 'Étudiant au baccalauréat', 'Des cours vivants : on a l’impression d’y être.'], ['Mélissa G.', 'Organisatrice, bibliothèque municipale', 'Sa conférence a fait salle comble, et le public en redemande.']] },
        form: { title: 'Inviter à une conférence', text: 'Étudiants, organisateurs ou médias : écrivez-moi pour une question, une conférence ou une entrevue.' } },
      en: { id: ['Dr. Olivia Grant', 'History lecturer', 'U.S. and North American history · Public speaker', 'Boston University'], ct: ['+1 617 555-0182', 'olivia.grant@email.com', 'oliviagrant.com'], so: { linkedin: 'https://linkedin.com/in/', youtube: 'https://youtube.com/' },
        primary: 'form',
        about: ['Teaching & research', 'With a Ph.D. in history, I have taught U.S. and North American history to undergraduates since 2015.\nI also give public talks in libraries, museums and companies.'],
        services: { title: 'Courses & talks', items: [['HIS 120 · Early American History', 'Undergraduate, fall semester'], ['HIS 231 · North America, 1760 – 1867', 'Undergraduate, spring semester'], ['Public talk', '60 to 90 minutes, on request', 'On request']] },
        parcours: { title: 'Background', items: [['Ph.D. in History · 2015', 'Dissertation on colonial trade networks'], ['Lecturer · since 2015', 'Department of History'], ['Exhibition curator · 2022', 'Regional history museum']] },
        projects: { title: 'Publications', items: [['Merchants of the River', 'Book, 2021 · Regional history award'], ['Article: The Fur Trade', 'History journal, 2023'], ['Podcast: History in 20 Minutes', '45 episodes']] },
        docs: { title: 'Documents', items: [['HIS 120 syllabus (PDF)', 'https://example.com/syllabus.pdf'], ['Publication list', 'https://example.com/publications'], ['Podcast', 'https://example.com/podcast']] },
        hours: { title: 'Office hours', rows: [['Tuesday', '1 pm – 3 pm'], ['Thursday', '10 am – 12 pm']], note: 'Office 312 or video call, by appointment' },
        reviews: { title: 'What students say', items: [['Anthony L.', 'Undergraduate student', 'Lively lectures: you feel like you’re there.'], ['Melissa G.', 'Organizer, public library', 'Her talk filled the room, and people want more.']] },
        form: { title: 'Invite me to speak', text: 'Students, organizers or media: write to me for a question, a talk or an interview.' } } }),

    /* ---------- Conseiller d'orientation ---------- */
    P({ id: 'orientation', icon: 'compass', rec: 'd2', n: ['Conseiller d’orientation', 'Career counselor'], ex: ['Choix de carrière, retour aux études', 'Career choices, going back to school'],
      pal: [pal('Turquoise', '#0f5e63', '#f4c95d'), pal('Bleu', '#1d4ed8', '#fdba74'), pal('Sauge', '#3f5a4a', '#e7d3b0'), pal('Prune', '#5b2a4a', '#f9c6d6'), pal('Terracotta', '#9a3412', '#fde68a'), pal('Graphite', '#27272a', '#86efac')],
      M: { portrait: '1557862921-37829c790f19', cover: '1573497620053-ea5300f94f21', gal: ['1511376979163-f804dff7ad7b', '1714976694525-71eb29a7c500', '1573495804664-b1c0849525af', '1551836022-d5d88e9218df'], cards: ['1511376979163-f804dff7ad7b', '1714976694525-71eb29a7c500', '1573495804664-b1c0849525af'] },
      fr: { id: ['Jason Reed', 'Conseiller d’orientation', 'Adolescents et adultes · Choix de carrière, réorientation, retour aux études', 'Cabinet Cap Avenir'], ct: ['+1 450 555-0139', 'jason@capavenir.ca', 'capavenir.ca'], so: { linkedin: 'https://linkedin.com/in/' },
        primary: 'booking',
        about: ['Trouver sa voie', 'Membre de l’ordre professionnel des conseillers d’orientation, j’accompagne depuis 12 ans les jeunes et les adultes qui se questionnent sur leur avenir.\nTests d’intérêts et de personnalité, exploration des métiers, plan d’action concret : on avance ensemble, à votre rythme.'],
        services: { title: 'Services', items: [['Bilan d’orientation · jeunes', '3 rencontres + tests d’intérêts', '450 $'], ['Réorientation de carrière · adultes', '4 rencontres + plan d’action', '580 $'], ['Rencontre ponctuelle', '60 minutes, en personne ou en ligne', '120 $']] },
        parcours: { title: 'Formation', items: [['Maîtrise en orientation', 'Université de Sherbrooke'], ['Conseiller d’orientation · depuis 2013', 'Écoles secondaires, puis pratique privée']] },
        booking: { title: 'Prendre rendez-vous', label: 'Réserver une rencontre', url: 'https://calendly.com/', text: 'Premier appel de 15 minutes offert pour voir si je peux vous aider.' },
        hours: { title: 'Disponibilités', rows: [['Lundi – Jeudi', '9 h – 20 h'], ['Vendredi', '9 h – 16 h']], note: 'Rencontres en personne à Longueuil ou en ligne' },
        location: { title: 'Le cabinet', address: '825, rue Saint-Laurent Ouest, Longueuil (Québec) J4K 2V1', access: 'Métro Longueuil · Stationnement gratuit' },
        reviews: { title: 'Témoignages', items: [['Camille D.', 'Élève de secondaire 5', 'Je savais enfin quoi choisir au cégep, et pourquoi.'], ['Patrick L.', '42 ans, réorientation', 'J’ai changé de carrière avec un plan clair. Le meilleur investissement de ma vie.']] },
        form: { title: 'Me contacter', text: 'Parlez-moi de votre situation en quelques mots, je vous réponds sous 24 h.' } },
      en: { id: ['Jason Reed', 'Career counselor', 'Teens & adults · Career choices, career change, going back to school', 'Next Step Counseling'], ct: ['+1 303 555-0139', 'jason@nextstepcounseling.com', 'nextstepcounseling.com'], so: { linkedin: 'https://linkedin.com/in/' },
        primary: 'booking',
        about: ['Find your path', 'A licensed career counselor for 12 years, I help teens and adults who are unsure about their future.\nInterest and personality assessments, career exploration, a concrete action plan: we move forward together, at your pace.'],
        services: { title: 'Services', items: [['Career assessment · teens', '3 sessions + interest inventory', '$450'], ['Career change · adults', '4 sessions + action plan', '$580'], ['Single session', '60 minutes, in person or online', '$120']] },
        parcours: { title: 'Education', items: [['M.A. in Counseling', 'University of Denver'], ['Career counselor · since 2013', 'High schools, then private practice']] },
        booking: { title: 'Book an appointment', label: 'Book a session', url: 'https://calendly.com/', text: 'Free 15-minute call to see if I can help.' },
        hours: { title: 'Availability', rows: [['Monday – Thursday', '9 am – 8 pm'], ['Friday', '9 am – 4 pm']], note: 'In person in Denver or online' },
        location: { title: 'The office', address: '1600 Broadway, Denver, CO 80202', access: 'Light rail – 16th & California · Parking garage' },
        reviews: { title: 'Testimonials', items: [['Chloe D.', 'High school senior', 'I finally knew which college major to pick, and why.'], ['Patrick L.', '42, career change', 'I changed careers with a clear plan. Best investment of my life.']] },
        form: { title: 'Contact me', text: 'Tell me about your situation in a few words, I’ll reply within 24 hours.' } } }),

    /* ---------- Orthopédagogue ---------- */
    P({ id: 'orthopedagogue', icon: 'puzzle', rec: 'd9', n: ['Orthopédagogue', 'Learning specialist'], ex: ['Dyslexie, TDAH, difficultés d’apprentissage', 'Dyslexia, ADHD, learning difficulties'],
      pal: [pal('Lavande', '#5b4a8a', '#fde68a'), pal('Menthe', '#2f6b5f', '#fecaca'), pal('Ciel', '#0369a1', '#fed7aa'), pal('Pêche', '#b4532a', '#c7d2fe'), pal('Vert', '#3f6212', '#fbcfe8'), pal('Marine', '#1e3a5f', '#a7f3d0')],
      M: { portrait: '1583468991267-3f068b607ae1', cover: '1599689868384-59cb2b01bb21', gal: ['1581544291234-31340be4b1b8', '1539632346654-dd4c3cffad8c', '1589206946274-929e4da3996b', '1549737221-bef65e2604a6'], cards: ['1581544291234-31340be4b1b8', '1539632346654-dd4c3cffad8c', '1589206946274-929e4da3996b'] },
      fr: { id: ['Laura Hughes', 'Orthopédagogue', 'Dyslexie, dysorthographie, TDAH · Primaire et secondaire', 'Clinique Les Mots Clés'], ct: ['+1 819 555-0153', 'laura@lesmotscles.ca', 'lesmotscles.ca'], so: { facebook: 'https://facebook.com/' },
        primary: 'booking',
        about: ['Accompagner chaque enfant', 'Orthopédagogue depuis 11 ans, j’évalue et j’accompagne les enfants qui ont des difficultés en lecture, en écriture ou en mathématiques.\nJe travaille en lien avec l’école et les parents, avec des stratégies concrètes et beaucoup de bienveillance.'],
        services: { title: 'Services', items: [['Évaluation orthopédagogique', 'Tests, rapport écrit et recommandations', '650 $'], ['Séance de rééducation', '50 minutes, en clinique ou en ligne', '90 $'], ['Rencontre avec l’école', 'Plan d’intervention, sur demande', '90 $']] },
        skills: { title: 'Difficultés accompagnées', tags: 'Dyslexie, Dysorthographie, Dyscalculie, TDAH, Méthodes de travail, Anxiété de performance' },
        parcours: { title: 'Formation', items: [['Baccalauréat en adaptation scolaire', 'Université du Québec à Trois-Rivières'], ['Orthopédagogue en clinique privée · depuis 2014', 'Plus de 400 enfants accompagnés']] },
        booking: { title: 'Prendre rendez-vous', label: 'Réserver une évaluation', url: 'https://calendly.com/', text: 'Reçus pour assurances fournis.' },
        gallery: { title: 'À la clinique', caps: ['Jeux de lettres', 'Apprendre en jouant', 'En classe', 'Le plaisir de lire'] },
        location: { title: 'La clinique', address: '450, boulevard des Récollets, Trois-Rivières (Québec) G8Z 3W7', access: 'Stationnement gratuit · Accès adapté' },
        reviews: { title: 'Les parents en parlent', items: [['Annie B.', 'Mère de Thomas, 9 ans', 'Thomas lit maintenant pour le plaisir. Un vrai changement à la maison.'], ['Louis-Philippe R.', 'Père d’une élève de secondaire 1', 'Le rapport d’évaluation nous a enfin aidés à comprendre notre fille.']] },
        form: { title: 'Me contacter', text: 'Âge de l’enfant, difficultés observées : écrivez-moi, je vous rappelle pour en discuter.' } },
      en: { id: ['Laura Hughes', 'Learning specialist', 'Dyslexia, dysgraphia, ADHD · K–12', 'Key Words Learning Center'], ct: ['+1 312 555-0153', 'laura@keywordslearning.com', 'keywordslearning.com'], so: { facebook: 'https://facebook.com/' },
        primary: 'booking',
        about: ['Supporting every child', 'A learning specialist for 11 years, I assess and support children who struggle with reading, writing or math.\nI work with schools and parents, using concrete strategies and plenty of kindness.'],
        services: { title: 'Services', items: [['Educational assessment', 'Testing, written report and recommendations', '$750'], ['Intervention session', '50 minutes, in office or online', '$95'], ['School meeting', 'IEP / 504 plan, on request', '$95']] },
        skills: { title: 'Areas of support', tags: 'Dyslexia, Dysgraphia, Dyscalculia, ADHD, Study skills, Test anxiety' },
        parcours: { title: 'Education', items: [['M.Ed. in Special Education', 'Northwestern University'], ['Learning specialist in private practice · since 2014', 'Over 400 children supported']] },
        booking: { title: 'Book an appointment', label: 'Book an assessment', url: 'https://calendly.com/', text: 'Superbills provided for insurance.' },
        gallery: { title: 'At the center', caps: ['Letter games', 'Learning through play', 'In class', 'The joy of reading'] },
        location: { title: 'The center', address: '2045 W Belmont Ave, Chicago, IL 60618', access: 'Free parking · Accessible entrance' },
        reviews: { title: 'What parents say', items: [['Annie B.', 'Mom of Thomas, 9', 'Thomas now reads for fun. A real change at home.'], ['Lewis R.', 'Dad of a 7th grader', 'The assessment report finally helped us understand our daughter.']] },
        form: { title: 'Contact me', text: 'Your child’s age, the difficulties you’ve noticed: write to me and I’ll call you back.' } } }),

    /* ---------- Directeur d'école ---------- */
    P({ id: 'directeur', icon: 'school', rec: 'd6', n: ['Directeur d’école', 'School principal'], ex: ['École primaire ou secondaire, établissement privé', 'Elementary or high school, private school'],
      pal: [pal('Marine', '#1e3a5f', '#f2c14e'), pal('Bordeaux', '#6b1d2a', '#e9c46a'), pal('Vert école', '#1f4d3a', '#f4d06f'), pal('Bleu roi', '#1d3fa8', '#fca5a5'), pal('Ardoise', '#334155', '#7dd3fc'), pal('Brique', '#8c3b2a', '#fde68a')],
      M: { portrait: '1517598024396-46c53fb391a1', cover: '1591123120675-6f7f1aae0e5b', gal: ['1580582932707-520aed937b7b', '1509062522246-3755977927d7', '1577896851231-70ef18881754', '1592066575517-58df903152f2'], cards: ['1509062522246-3755977927d7', '1577896851231-70ef18881754', '1580582932707-520aed937b7b'] },
      fr: { id: ['Robert Hayes', 'Directeur', 'École primaire des Érables · 480 élèves, préscolaire à 6e année', 'Centre de services scolaire'], ct: ['+1 450 555-0119', 'direction.erables@ecole.qc.ca', 'ecoledeserables.ca'], so: { facebook: 'https://facebook.com/' },
        primary: 'save',
        about: ['Mot du directeur', 'Bienvenue à l’École des Érables ! Notre équipe de 45 personnes accompagne chaque enfant pour qu’il apprenne dans un milieu sécuritaire, stimulant et bienveillant.\nN’hésitez pas à me contacter pour une visite ou une question sur l’inscription.'],
        services: { title: 'Notre école', items: [['Préscolaire 4 ans et 5 ans', 'Classes de maternelle'], ['Primaire, 1re à 6e année', 'Volet sciences et anglais enrichi'], ['Service de garde', '7 h à 18 h, journées pédagogiques'], ['Parascolaire', 'Robotique, soccer, théâtre, chorale']] },
        docs: { title: 'Documents utiles', items: [['Calendrier scolaire (PDF)', 'https://example.com/calendrier.pdf'], ['Inscription en ligne', 'https://example.com/inscription'], ['Liste des fournitures', 'https://example.com/fournitures.pdf'], ['Code de vie', 'https://example.com/code.pdf']] },
        gallery: { title: 'La vie à l’école', caps: ['Nos classes', 'En apprentissage', 'Lecture en groupe', 'L’école'] },
        hours: { title: 'Heures du secrétariat', rows: [['Lundi – Vendredi', '7 h 45 – 16 h'], ['Été', 'Horaire réduit, sur rendez-vous']], note: 'Absences d’élèves : appelez avant 8 h 30' },
        location: { title: 'Nous trouver', address: '1250, rue des Érables, Terrebonne (Québec) J6W 2K8', access: 'Débarcadère rue des Pins · Stationnement des visiteurs' },
        form: { title: 'Écrire à la direction', text: 'Parents, futurs parents ou partenaires : écrivez-nous, nous vous répondons sous 48 h.' } },
      en: { id: ['Robert Hayes', 'Principal', 'Maple Grove Elementary · 480 students, pre-K to 5th grade', 'Public School District'], ct: ['+1 614 555-0119', 'principal@maplegrove.k12.us', 'maplegroveelementary.org'], so: { facebook: 'https://facebook.com/' },
        primary: 'save',
        about: ['A word from the principal', 'Welcome to Maple Grove Elementary! Our team of 45 helps every child learn in a safe, engaging and caring environment.\nFeel free to contact me for a tour or an enrollment question.'],
        services: { title: 'Our school', items: [['Pre-K and Kindergarten', 'Half and full day'], ['Grades 1 to 5', 'STEM and enriched reading programs'], ['Before & after care', '7 am to 6 pm, teacher workdays'], ['After-school clubs', 'Robotics, soccer, drama, choir']] },
        docs: { title: 'Useful documents', items: [['School calendar (PDF)', 'https://example.com/calendar.pdf'], ['Online enrollment', 'https://example.com/enroll'], ['Supply list', 'https://example.com/supplies.pdf'], ['Code of conduct', 'https://example.com/conduct.pdf']] },
        gallery: { title: 'School life', caps: ['Our classrooms', 'Learning', 'Group reading', 'The school'] },
        hours: { title: 'Front office hours', rows: [['Monday – Friday', '7:45 am – 4 pm'], ['Summer', 'Reduced hours, by appointment']], note: 'Student absences: call before 8:30 am' },
        location: { title: 'Find us', address: '1250 Maple Grove Rd, Columbus, OH 43214', access: 'Drop-off on Pine St · Visitor parking' },
        form: { title: 'Write to the principal', text: 'Parents, future parents or partners: write to us, we reply within 48 hours.' } } }),

    /* ---------- Formateur en entreprise ---------- */
    P({ id: 'formateur', icon: 'users', rec: 'd1', n: ['Formateur en entreprise', 'Corporate trainer'], ex: ['Formations, ateliers, coaching d’équipe', 'Training, workshops, team coaching'],
      pal: [pal('Bleu pro', '#1e40af', '#fbbf24'), pal('Graphite', '#18181b', '#f97316'), pal('Émeraude', '#065f46', '#fcd34d'), pal('Bordeaux', '#7f1d1d', '#fde68a'), pal('Indigo', '#3730a3', '#5eead4'), pal('Acier', '#334155', '#a3e635')],
      M: { portrait: '1560250097-0b93528c311a', cover: '1542744173-8e7e53415bb0', gal: ['1524178232363-1fb2b075b655', '1591115765373-5207764f72e7', '1556761175-5973dc0f32e7', '1577962917302-cd874c4e31d2'], cards: ['1524178232363-1fb2b075b655', '1591115765373-5207764f72e7', '1577962917302-cd874c4e31d2'] },
      fr: { id: ['Michael Turner', 'Formateur en entreprise', 'Leadership, communication et service à la clientèle · Formations certifiées', 'Turner Formation'], ct: ['+1 514 555-0166', 'michael@turnerformation.ca', 'turnerformation.ca'], so: { linkedin: 'https://linkedin.com/in/' },
        primary: 'form',
        about: ['Des formations qui changent les pratiques', 'Formateur agréé, j’accompagne depuis 15 ans les PME et les grandes entreprises dans le développement de leurs gestionnaires et de leurs équipes.\nAteliers pratiques, mises en situation et suivi après la formation : vos équipes repartent avec des outils qu’elles utilisent dès le lendemain.'],
        services: { title: 'Formations', items: [['Leadership pour nouveaux gestionnaires', '2 jours, en entreprise ou en ligne', 'dès 2 900 $'], ['Communication et gestion des conflits', '1 jour, jusqu’à 15 participants', 'dès 1 600 $'], ['Service à la clientèle d’exception', 'Demi-journée, atelier pratique', 'dès 950 $'], ['Coaching de gestionnaire', '6 rencontres individuelles', '1 800 $']] },
        projects: { title: 'Réalisations', items: [['Programme de leadership', '120 gestionnaires formés dans une chaîne de quincailleries'], ['Ateliers de communication', 'Hôpital régional · 300 employés'], ['Service client', 'Satisfaction client +18 points dans une banque']] },
        skills: { title: 'Expertises', tags: 'Leadership, Communication, Gestion du changement, Service à la clientèle, Travail d’équipe, Formation de formateurs' },
        docs: { title: 'Documents', items: [['Catalogue des formations (PDF)', 'https://example.com/catalogue.pdf'], ['Formations admissibles à la loi du 1 %', 'https://example.com/admissibles']] },
        reviews: { title: 'Ce qu’en disent nos clients', items: [['Nancy G.', 'Directrice RH, manufacturier', 'Nos gestionnaires appliquent encore ses outils deux ans plus tard.'], ['Éric T.', 'Directeur des opérations', 'Concret, dynamique et adapté à notre réalité. On le recommande.']] },
        form: { title: 'Demander une soumission', text: 'Nombre de participants, thème, dates souhaitées : je vous envoie une proposition sous 48 h.' } },
      en: { id: ['Michael Turner', 'Corporate trainer', 'Leadership, communication & customer service · Certified programs', 'Turner Training'], ct: ['+1 404 555-0166', 'michael@turnertraining.com', 'turnertraining.com'], so: { linkedin: 'https://linkedin.com/in/' },
        primary: 'form',
        about: ['Training that changes how people work', 'A certified trainer for 15 years, I help small businesses and large companies develop their managers and teams.\nHands-on workshops, role-plays and post-training follow-up: your teams leave with tools they use the very next day.'],
        services: { title: 'Programs', items: [['Leadership for new managers', '2 days, on-site or online', 'from $2,900'], ['Communication & conflict resolution', '1 day, up to 15 participants', 'from $1,600'], ['Outstanding customer service', 'Half day, hands-on workshop', 'from $950'], ['Manager coaching', '6 one-on-one sessions', '$1,800']] },
        projects: { title: 'Results', items: [['Leadership program', '120 managers trained at a hardware chain'], ['Communication workshops', 'Regional hospital · 300 employees'], ['Customer service', '+18 points in customer satisfaction at a bank']] },
        skills: { title: 'Expertise', tags: 'Leadership, Communication, Change management, Customer service, Teamwork, Train-the-trainer' },
        docs: { title: 'Documents', items: [['Training catalog (PDF)', 'https://example.com/catalog.pdf'], ['Case studies', 'https://example.com/cases']] },
        reviews: { title: 'What clients say', items: [['Nancy G.', 'HR Director, manufacturer', 'Our managers still use his tools two years later.'], ['Eric T.', 'Operations Director', 'Practical, energetic and tailored to our reality. Highly recommended.']] },
        form: { title: 'Request a quote', text: 'Number of participants, topic, preferred dates: I’ll send you a proposal within 48 hours.' } } }),
  ];

  const first = PROFILES[0];
  const education = {
    id: 'education', code: 'F21', name: 'Éducation', icon: 'graduation-cap', active: true, rec: first.rec,
    ex: 'Étudiant, professeur, stagiaire, éducateur…',
    palettes: first.palettes, blocks: BLOCKS, demo: first.demo, demoEn: first.demoEn, profiles: PROFILES,
  };
  /* Placé juste après « Carte professionnelle et réseautage » */
  const i = NFC.SECTORS.findIndex((s) => s.id === 'pro');
  NFC.SECTORS.splice(i < 0 ? NFC.SECTORS.length : i + 1, 0, education);
  NFC.MEDIA = NFC.MEDIA || {};
  NFC.MEDIA.education = first.media;

  /* Anglais : nom du secteur et titres des sections */
  Object.assign(window.NFC_EN_UI || (window.NFC_EN_UI = {}), {
    'Éducation': 'Education', 'Étudiant, professeur, stagiaire, éducateur…': 'Student, teacher, intern, educator…',
    'Parcours': 'Background', 'Compétences': 'Skills', 'Projets': 'Projects', 'En images': 'In pictures', 'CV et documents': 'Resume & documents',
    'Langues': 'Languages', 'Disponibilités': 'Availability', 'Où me trouver': 'Where to find me', 'Recommandations': 'References', 'Me contacter': 'Contact me',
  });
})();
